version: '3.8'

services:
  afk-terminal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7681:7681"
    environment:
      - CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}
    volumes:
      - ./workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: unless-stopped